### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by aunrea** [WilliamFitzjohn/MMM-TwitchAlert#1]
I have installed this module. I have checked my config many times and it is correct. But all I ever see on my MagicMirror is "Loading...". 

This is my config:
` {
module: "MMM-TwitchAlert",
position: "bottom_left",			
config: {
client_id: "**************************",
client_secret: "********************",
live_only: false,
show_live_badge: true,
update_interval: 5, //minutes
alignment: 'left',
streamers: [
"goodtimeswithscar",
"pearlescentmoon",
"impulsesv",
"zedaphplays",
],
},
},`

Of course the **** are the actual id and secret.

**Comment by aunrea** [comment]
Nevermind it decided to work after I asked the question.

**Comment by WilliamFitzjohn** [comment]
@aunrea Thanks for bringing this to my attention, I have a rough idea of what could've gone wrong and it shouldn't effect you anymore. I'll take a look into fixing it for future users.
