### ISSUE TITLE
show_live_badge: false, has no effect

### ISSUE THREAD

**Issue by Coernel82** [WilliamFitzjohn/MMM-TwitchAlert#3]
For my understanding the setting ``show_live_badge: false,`` should hide the round picture of the streamer in front of the streamer's name. Unfortunately it doesn't.

**Comment by WilliamFitzjohn** [comment]
Sorry for the inconvenience, I'll try to reproduce the bug and fix it when I can!

**Comment by WilliamFitzjohn** [comment]
@Coernel82 I started troubleshooting but realized there has been a misunderstanding of the setting. I intended the setting to only hide the red "LIVE" badge and keep the profile picture of the streamer visible regardless of this setting. If you wish to hide the profile pictures, I can add a setting for that too.

**Comment by Coernel82** [comment]
Hi William, yes indeed that was a misunderstanding. I mean the profile picture. This would be really great if you add this option.
```java
hideProfilePic = true,

```
I just made my MagicMirror²bworking on an E-Ink screen via SPI interface and I am lacking space with my 800 x 460 pixels!

**Comment by Coernel82** [comment]
> Hi William, yes indeed that was a misunderstanding. I mean the profile picture. This would be really great if you add this option.
> ```java
> hideProfilePic = true,
> 
> ```
> I just made my MagicMirror²bworking on an E-Ink screen via SPI interface and I am lacking space with my 800 x 460 pixels!

Actually to stay in your writing:
```java
show_profile_pic = false,

```

**Comment by Coernel82** [comment]
I opened a pull request. I think I did it right. My JavaScript-Noob-Factor is 9 out of 10.
